services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data
  orchastrator:
    image: orchastrator
    build:
      context: ./orchastrator
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
  mastra:
    image: mastra
    build:
      context: ./mastra
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3001
  # svelte:
  #   image: svelte
  #   build:
  #     context: ./svelte
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 3002:3002
volumes:
  pgdata:
